In [0]:
import numpy as np  #importing numpy

In [0]:
list1 = [1, 2, 3, 4, 5]   #creating list

In [0]:
arr1 = np.array(list1)

In [0]:
list2 = [range(1,5), range(5,10)]   # making list inside a list

In [0]:
arr2 = np.array(list2)

In [0]:
arr2.tolist()

[range(1, 5), range(5, 10)]

In [0]:
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [0]:
np.zeros((3, 6))  #number of rows and colums: 3 rows and 6 column

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [0]:
np.ones(10)    # multiplying 10 times

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [0]:
np.linspace(0, 1, 5)   # uniform distribution between 0 and 1, 5 times

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [0]:
np.logspace(0, 3, 4)

array([   1.,   10.,  100., 1000.])

In [0]:
int_array = np.arange(5)


In [0]:
arr1.dtype       #checking the type 


dtype('int64')

In [0]:
arr2.dtype

dtype('O')

In [0]:
arr2.ndim


1

In [0]:
arr2.shape

(2,)

In [0]:
arr2.dtype

dtype('O')

In [0]:
arr2.size

2

In [0]:
len(arr2)

2

In [0]:
arr2.size

2

In [0]:
arr = np.arange(10, dtype=float).reshape((2, 5))
print(arr.shape)

(2, 5)


In [0]:
print(arr.reshape(5, 2))

[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]


In [0]:
a = np.array([0, 1])

In [0]:
a_col = a[:, np.newaxis]
print(a_col)

[[0]
 [1]]


In [0]:
print(a_col.T)

[[0 1]]


In [0]:
arr_flt = arr.flatten()
arr_flt[0] = 33
print(arr_flt)
print(arr)

[33.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]


In [0]:
arr_flt = arr.ravel()
arr_flt[0] = 33
print(arr_flt)
print(arr)

[33.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
[[33.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]]


In [0]:
a = np.array([0, 1])
b = np.array([2, 3])

ab = np.stack((a, b)).T
print(ab)

[[0 2]
 [1 3]]


In [0]:
arr = np.arange(10, dtype=float).reshape((2, 5))

arr[0]

array([0., 1., 2., 3., 4.])

In [0]:
arr[0,3]

3.0

In [0]:
arr[0][3]

3.0

In [0]:
arr[0, :]

array([0., 1., 2., 3., 4.])

In [0]:
arr[:, 0]

array([0., 5.])

In [0]:
arr[:, :2]

array([[0., 1.],
       [5., 6.]])

In [0]:
arr[:, 2:]

array([[2., 3., 4.],
       [7., 8., 9.]])

In [0]:
arr2 = arr[:, 1:4]

In [0]:
print(arr2)

[[1. 2. 3.]
 [6. 7. 8.]]


In [0]:
arr2[0, 0] = 33
print(arr2)
print(arr)

[[33.  2.  3.]
 [ 6.  7.  8.]]
[[ 0. 33.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]]


In [0]:
print(arr[0, ::-1])

[ 4.  3.  2. 33.  0.]


In [0]:
arr2 = arr[:, [1, 2, 3]]
print(arr2)

[[33.  2.  3.]
 [ 6.  7.  8.]]


In [0]:
arr2[0, 0] = 44
print(arr2)

[[44.  2.  3.]
 [ 6.  7.  8.]]


In [0]:
print(arr)

[[ 0. 33.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]]


In [0]:
arr2 = arr[arr >5]
print(arr2)

[33.  6.  7.  8.  9.]


In [0]:
arr2[0] = 44

In [0]:
print(arr2)
print(arr)

[44.  6.  7.  8.  9.]
[[ 0. 33.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]]


In [0]:
arr [arr >5] = 0
print(arr)

[[0. 0. 2. 3. 4.]
 [5. 0. 0. 0. 0.]]


In [0]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob'])

In [0]:
names == 'Bob'

array([ True, False, False,  True])

In [0]:
names[names != 'Bob']

array(['Joe', 'Will'], dtype='<U4')

In [0]:
(names == 'Bob') | (names == 'Will')

array([ True, False,  True,  True])

In [0]:
names[names != 'Bob'] = 'Joe'

In [0]:
np.unique(names)

array(['Bob', 'Joe'], dtype='<U4')

In [0]:
nums = np.arange(5)

In [0]:
nums * 10

array([ 0, 10, 20, 30, 40])

In [0]:
num = np.sqrt(nums)
np.ceil(nums)

array([0., 1., 2., 3., 4.])

In [0]:
np.isnan(nums)

array([False, False, False, False, False])

In [0]:
nums + np.arange(5)

array([0, 2, 4, 6, 8])

In [0]:
np.maximum(nums, np.array([1, -2, 3, -4, 5]))

array([1, 1, 3, 3, 5])

In [0]:
vec1 = np.random.rand(10)
vec2 = np.random.rand(10)
dist = np.sqrt(np.sum((vec1 - vec2) **2))

In [0]:
rnd = np.random.randn(4, 2)

In [0]:
rnd.mean()

0.6787866358786105

In [0]:
rnd.std()

0.6742214363560326

In [0]:
rnd.argmin() #i didn't understand this line can you help me

0

In [0]:
rnd.sum()

5.430293087028884

In [0]:
rnd.sum(axis=0)

array([3.48223064, 1.94806245])

In [0]:
rnd.sum(axis=1)

array([0.77507584, 1.83472514, 0.29545231, 2.52503979])

In [0]:
(rnd > 0).sum()

7

In [0]:
(rnd > 0).any()

True

In [0]:
(rnd > 0).all()

False

In [0]:
np.random.seed(12234)

In [0]:
np.random.rand(2, 3)

array([[0.00630595, 0.20303476, 0.76478993],
       [0.55513384, 0.74358546, 0.93777808]])

In [0]:
np.random.randn(10)

array([-2.79962074e-01,  1.31281104e+00, -9.27155784e-01, -4.01302169e-01,
       -2.31085929e+00, -2.08460156e+00,  4.59241643e-01,  1.62191344e+00,
        1.94515120e-01, -2.08631547e-03])

In [0]:
np.random.randint(0, 2, 10)

array([0, 0, 0, 1, 1, 0, 1, 1, 1, 1])

In [0]:
a = np.array ([[0, 0, 0], [10, 10, 10], [20, 20, 20], [30, 30, 30]])
b = np.array([0, 1, 2])
print(a+b)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [0]:
a = 12
print(a)

12


In [0]:
x = np.random.randn(4,2)


In [120]:
X = np.random.randn(4,2)
X.argmin(axis = 0),X.argmin(axis = 1)


# We can also get value like this
print(X[:,0].min(),X[:,1].min())
print(X[:,:].min())

-0.05014604593747791 -0.44590868174241155
-0.44590868174241155


In [0]:
def standardize(X):
    norm_X =( X-np.mean(X))/np.std(X)
    return norm_X

In [0]:
Z = standardize(X)

In [123]:
Z.mean()
Z.std()

1.0