In [0]:
import numpy as np  #importing numpy

In [0]:
list1 = [1, 2, 3, 4, 5]   #creating list

In [0]:
arr1 = np.array(list1) #converting list to array

In [0]:
list2 = [range(1,5), range(5,10)]   # making list inside a list

In [0]:
arr2 = np.array(list2)   #converting the list into array

In [0]:
arr2.tolist() # converting back to list

[range(1, 5), range(5, 10)]

In [0]:
np.zeros(10)  #create a numpy array of length 10


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [0]:
np.zeros((3, 6))  #number of rows and colums: 3 rows and 6 column

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [0]:
np.ones(10)    # multiplying 10 times

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [0]:
np.linspace(0, 1, 5)   # uniform distribution between 0 and 1, 5 times

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [0]:
np.logspace(0, 3, 4)  # creates 10^0 to 10^3, creating 4 points

array([   1.,   10.,  100., 1000.])

In [0]:
int_array = np.arange(5)  # this command provide an array output, ranging from 0 to 4.


In [0]:
arr1.dtype       #checking the type 


dtype('int64')

In [0]:
arr2.dtype

dtype('O')

In [0]:
arr2.ndim
#provides the number of dimensions for the given array.

1

In [0]:
arr2.shape
#provides the number of rows and columns (shape of the array)

(2,)

In [0]:
arr2.dtype
#provides the data type.

dtype('O')

In [0]:
arr2.size
#provides the total number of elements (entries) in the array.

2

In [0]:
len(arr2)

2

In [0]:
arr2.size

2

In [0]:
arr = np.arange(10, dtype=float).reshape((2, 5))
print(arr.shape)
#This creates an array of range from 0 to 9,
#with float entries and arranging them in a fashion such that
#there are 2 rows and 5 columns

(2, 5)


In [0]:
print(arr.reshape(5, 2))
#This reshapes the array into the fashion such that
#it has 5 rows and 2 columns

[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]


In [0]:
a = np.array([0, 1])

In [0]:
a_col = a[:, np.newaxis]
print(a_col)

[[0]
 [1]]


In [0]:
print(a_col.T)

[[0 1]]


In [0]:
arr_flt = arr.flatten() #makes it a column vector(only 1 row)
arr_flt[0] = 33   #replaces the index 0 value as 33.
print(arr_flt)
print(arr)

[33.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]


In [0]:
arr_flt = arr.ravel()
arr_flt[0] = 33
print(arr_flt)
print(arr)

[33.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
[[33.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]]


In [0]:
a = np.array([0, 1])
b = np.array([2, 3])

ab = np.stack((a, b)).T
print(ab)

#Stacks two arrays together,
t#hen prints out their transposed stacking 'ab'

[[0 2]
 [1 3]]


In [0]:
arr = np.arange(10, dtype=float).reshape((2, 5))

arr[0]

array([0., 1., 2., 3., 4.])

In [0]:
arr[0,3]

# there is a mistake in the tutorial.
# 0th row, 3rd colums, it returns 3.0.

3.0

In [0]:
arr[0][3]

3.0

In [0]:
arr[0, :]
#returns 0th row, all columns.

array([0., 1., 2., 3., 4.])

In [0]:
arr[:, 0]
#returns all rows, 0th column.

array([0., 5.])

In [0]:
arr[:, :2]
#return all rows, but columns before index 2

array([[0., 1.],
       [5., 6.]])

In [0]:
arr[:, 2:]
#return all rows, but columns after index 2 (included)

array([[2., 3., 4.],
       [7., 8., 9.]])

In [0]:
arr2 = arr[:, 1:4]
#return all rows, but columns between index  1(included)
#and index 4 (excluded)

In [0]:
print(arr2)

[[1. 2. 3.]
 [6. 7. 8.]]


In [0]:
arr2[0, 0] = 33
print(arr2)
print(arr)
#slices the array, and changes the mentioned element, and  modifies the actual array as well.

[[33.  2.  3.]
 [ 6.  7.  8.]]
[[ 0. 33.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]]


In [0]:
print(arr[0, ::-1])

[ 4.  3.  2. 33.  0.]


In [0]:
arr2 = arr[:, [1, 2, 3]]
print(arr2)
# fancy indexing.  Returns all the rows and columns 1-3 (as mentioned inside the brackets)

[[33.  2.  3.]
 [ 6.  7.  8.]]


In [0]:
arr2[0, 0] = 44
print(arr2)
# modifies the first entry (0,0) to 44 in arr2

[[44.  2.  3.]
 [ 6.  7.  8.]]


In [0]:
print(arr)

[[ 0. 33.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]]


In [0]:
arr2 = arr[arr >5]
print(arr2)
# outputs only those entries which have value greater than 5.

[33.  6.  7.  8.  9.]


In [0]:
arr2[0] = 44
# modifies the first entry (33) to 44.

In [0]:
print(arr2)
print(arr)

[44.  6.  7.  8.  9.]
[[ 0. 33.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]]


In [0]:
arr [arr >5] = 0
print(arr)
# modifies all the entry values greater than 5 to 0.

[[0. 0. 2. 3. 4.]
 [5. 0. 0. 0. 0.]]


In [8]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob'])
print(names)
# creates an array, consisting of string entries.

['Bob' 'Joe' 'Will' 'Bob']


In [4]:
names == 'Bob'
# The output is array([ True, False, False,  True]) 
# which is a boolean array based on the entry 'Bob'

array([ True, False, False,  True])

In [9]:
names[names != 'Bob']
# returns all the entries which are not 'Bob'.

array(['Joe', 'Will'], dtype='<U4')

In [0]:
(names == 'Bob') | (names == 'Will')
#This boolean OR operation on the entries.

array([ True, False,  True,  True])

In [11]:
names[names != 'Bob'] = 'Joe'
print(names)

['Bob' 'Joe' 'Joe' 'Bob']


In [12]:
np.unique(names)
#returns the unqiue names, distinct ones

array(['Bob', 'Joe'], dtype='<U4')

In [14]:
nums = np.arange(5)
print(nums)

[0 1 2 3 4]


In [0]:
nums * 10  #multiply elements by 10 times

array([ 0, 10, 20, 30, 40])

In [15]:
num = np.sqrt(nums)   #square root of each elements
np.ceil(nums)          #round off to the closest integer

array([0., 1., 2., 3., 4.])

In [0]:
np.isnan(nums)   # check for NaN

array([False, False, False, False, False])

In [0]:
nums + np.arange(5)
#adds the corresonding entries (elements) of the given arrays.

array([0, 2, 4, 6, 8])

In [16]:
np.maximum(nums, np.array([1, -2, 3, -4, 5]))
#compares the given arrays and returns the highest values among the entries of the arrays being compared.

array([1, 1, 3, 3, 5])

In [0]:
vec1 = np.random.rand(10)
vec2 = np.random.rand(10)
#random number generator


dist = np.sqrt(np.sum((vec1 - vec2) **2))


In [24]:
rnd = np.random.randn(4, 2)
print(rnd)
# creates an array of random numbers, consisting of 4 rows and  cloumns

[[-0.67686456 -0.39968599]
 [-0.21567928  0.01818035]
 [-0.11869358 -1.79857705]
 [ 1.25703178 -0.29273474]]


In [0]:
rnd.mean()      #calculating mean

0.6787866358786105

In [0]:
rnd.std()  # calculating standard deviation

0.6742214363560326

In [19]:
rnd.argmin() #provides the index of the minimum value present in the array

0

In [0]:
rnd.sum()    #calculating sum of all the array entries

5.430293087028884

In [0]:
rnd.sum(axis=0)     #sum of columns

array([3.48223064, 1.94806245])

In [0]:
rnd.sum(axis=1)      #calculating sum of rows

array([0.77507584, 1.83472514, 0.29545231, 2.52503979])

In [22]:
(rnd > 0).sum()   #counts sum of all the positive values, and runds it off to the nearest integer

5

In [0]:
(rnd > 0).any()      #checks if any value is greater than 0

True

In [23]:
(rnd > 0).all()      #checks if all values are greater than 0

False

In [0]:
np.random.seed(12234)

In [0]:
np.random.rand(2, 3)
# random number array, with 2 rows and 3 columns

array([[0.00630595, 0.20303476, 0.76478993],
       [0.55513384, 0.74358546, 0.93777808]])

In [0]:
np.random.randn(10)
# random number array with 10 entries

array([-2.79962074e-01,  1.31281104e+00, -9.27155784e-01, -4.01302169e-01,
       -2.31085929e+00, -2.08460156e+00,  4.59241643e-01,  1.62191344e+00,
        1.94515120e-01, -2.08631547e-03])

In [0]:
np.random.randint(0, 2, 10)
# 10 numbers, either 0 or 1, distributed randomly.

array([0, 0, 0, 1, 1, 0, 1, 1, 1, 1])

In [0]:
a = np.array ([[0, 0, 0], [10, 10, 10], [20, 20, 20], [30, 30, 30]])
b = np.array([0, 1, 2])
print(a+b)
# adds the rwo array to each of the rows in the first input array

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [0]:
a = 12
print(a)

12


In [0]:
x = np.random.randn(4,2)


In [0]:
X = np.random.randn(4,2)
X.argmin(axis = 0),X.argmin(axis = 1)



(array([0, 2]), array([0, 1, 1, 1]))

In [0]:
def standardize(X):
    normalize_X =( X-np.mean(X))/np.std(X)
    return normalize_X

In [0]:
z = standardize(X)

In [0]:

z.mean()
z.std()

1.0